/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/summaries/data`; params?: Router.UnknownInputParams; } | { pathname: `/summaries`; params?: Router.UnknownInputParams; } | { pathname: `/tests/test-settings`; params?: Router.UnknownInputParams; } | { pathname: `/tests/test`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/AmericanQuestionComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/OrderingQuestionComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/OrderingQuestionResultComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/TestSummaryComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/services/testService`; params?: Router.UnknownInputParams; } | { pathname: `/tests/styles/testStyles`; params?: Router.UnknownInputParams; } | { pathname: `/summaries/[topic]`, params: Router.UnknownInputParams & { topic: string | number; } } | { pathname: `/summaries/view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/landing`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/summaries/data`; params?: Router.UnknownOutputParams; } | { pathname: `/summaries`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/test-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/test`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/components/AmericanQuestionComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/components/OrderingQuestionComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/components/OrderingQuestionResultComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/components/TestSummaryComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/services/testService`; params?: Router.UnknownOutputParams; } | { pathname: `/tests/styles/testStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/summaries/[topic]`, params: Router.UnknownOutputParams & { topic: string; } } | { pathname: `/summaries/view/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/landing${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/summaries/data${`?${string}` | `#${string}` | ''}` | `/summaries${`?${string}` | `#${string}` | ''}` | `/tests/test-settings${`?${string}` | `#${string}` | ''}` | `/tests/test${`?${string}` | `#${string}` | ''}` | `/tests/components/AmericanQuestionComponent${`?${string}` | `#${string}` | ''}` | `/tests/components/OrderingQuestionComponent${`?${string}` | `#${string}` | ''}` | `/tests/components/OrderingQuestionResultComponent${`?${string}` | `#${string}` | ''}` | `/tests/components/TestSummaryComponent${`?${string}` | `#${string}` | ''}` | `/tests/services/testService${`?${string}` | `#${string}` | ''}` | `/tests/styles/testStyles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/summaries/data`; params?: Router.UnknownInputParams; } | { pathname: `/summaries`; params?: Router.UnknownInputParams; } | { pathname: `/tests/test-settings`; params?: Router.UnknownInputParams; } | { pathname: `/tests/test`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/AmericanQuestionComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/OrderingQuestionComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/OrderingQuestionResultComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/components/TestSummaryComponent`; params?: Router.UnknownInputParams; } | { pathname: `/tests/services/testService`; params?: Router.UnknownInputParams; } | { pathname: `/tests/styles/testStyles`; params?: Router.UnknownInputParams; } | `/summaries/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/summaries/view/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/summaries/[topic]`, params: Router.UnknownInputParams & { topic: string | number; } } | { pathname: `/summaries/view/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
